 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/character_descriptors", type: :request do
  # CharacterDescriptor. As you add validations to CharacterDescriptor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CharacterDescriptor.create! valid_attributes
      get character_descriptors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      character_descriptor = CharacterDescriptor.create! valid_attributes
      get character_descriptor_url(character_descriptor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_character_descriptor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      character_descriptor = CharacterDescriptor.create! valid_attributes
      get edit_character_descriptor_url(character_descriptor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CharacterDescriptor" do
        expect {
          post character_descriptors_url, params: { character_descriptor: valid_attributes }
        }.to change(CharacterDescriptor, :count).by(1)
      end

      it "redirects to the created character_descriptor" do
        post character_descriptors_url, params: { character_descriptor: valid_attributes }
        expect(response).to redirect_to(character_descriptor_url(CharacterDescriptor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CharacterDescriptor" do
        expect {
          post character_descriptors_url, params: { character_descriptor: invalid_attributes }
        }.to change(CharacterDescriptor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post character_descriptors_url, params: { character_descriptor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested character_descriptor" do
        character_descriptor = CharacterDescriptor.create! valid_attributes
        patch character_descriptor_url(character_descriptor), params: { character_descriptor: new_attributes }
        character_descriptor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the character_descriptor" do
        character_descriptor = CharacterDescriptor.create! valid_attributes
        patch character_descriptor_url(character_descriptor), params: { character_descriptor: new_attributes }
        character_descriptor.reload
        expect(response).to redirect_to(character_descriptor_url(character_descriptor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        character_descriptor = CharacterDescriptor.create! valid_attributes
        patch character_descriptor_url(character_descriptor), params: { character_descriptor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested character_descriptor" do
      character_descriptor = CharacterDescriptor.create! valid_attributes
      expect {
        delete character_descriptor_url(character_descriptor)
      }.to change(CharacterDescriptor, :count).by(-1)
    end

    it "redirects to the character_descriptors list" do
      character_descriptor = CharacterDescriptor.create! valid_attributes
      delete character_descriptor_url(character_descriptor)
      expect(response).to redirect_to(character_descriptors_url)
    end
  end
end
