 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/character_backgrounds", type: :request do
  # CharacterBackground. As you add validations to CharacterBackground, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CharacterBackground.create! valid_attributes
      get character_backgrounds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      character_background = CharacterBackground.create! valid_attributes
      get character_background_url(character_background)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_character_background_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      character_background = CharacterBackground.create! valid_attributes
      get edit_character_background_url(character_background)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CharacterBackground" do
        expect {
          post character_backgrounds_url, params: { character_background: valid_attributes }
        }.to change(CharacterBackground, :count).by(1)
      end

      it "redirects to the created character_background" do
        post character_backgrounds_url, params: { character_background: valid_attributes }
        expect(response).to redirect_to(character_background_url(CharacterBackground.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CharacterBackground" do
        expect {
          post character_backgrounds_url, params: { character_background: invalid_attributes }
        }.to change(CharacterBackground, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post character_backgrounds_url, params: { character_background: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested character_background" do
        character_background = CharacterBackground.create! valid_attributes
        patch character_background_url(character_background), params: { character_background: new_attributes }
        character_background.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the character_background" do
        character_background = CharacterBackground.create! valid_attributes
        patch character_background_url(character_background), params: { character_background: new_attributes }
        character_background.reload
        expect(response).to redirect_to(character_background_url(character_background))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        character_background = CharacterBackground.create! valid_attributes
        patch character_background_url(character_background), params: { character_background: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested character_background" do
      character_background = CharacterBackground.create! valid_attributes
      expect {
        delete character_background_url(character_background)
      }.to change(CharacterBackground, :count).by(-1)
    end

    it "redirects to the character_backgrounds list" do
      character_background = CharacterBackground.create! valid_attributes
      delete character_background_url(character_background)
      expect(response).to redirect_to(character_backgrounds_url)
    end
  end
end
