 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/prompts", type: :request do
  # Prompt. As you add validations to Prompt, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Prompt.create! valid_attributes
      get prompts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      prompt = Prompt.create! valid_attributes
      get prompt_url(prompt)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_prompt_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      prompt = Prompt.create! valid_attributes
      get edit_prompt_url(prompt)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Prompt" do
        expect {
          post prompts_url, params: { prompt: valid_attributes }
        }.to change(Prompt, :count).by(1)
      end

      it "redirects to the created prompt" do
        post prompts_url, params: { prompt: valid_attributes }
        expect(response).to redirect_to(prompt_url(Prompt.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Prompt" do
        expect {
          post prompts_url, params: { prompt: invalid_attributes }
        }.to change(Prompt, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post prompts_url, params: { prompt: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prompt" do
        prompt = Prompt.create! valid_attributes
        patch prompt_url(prompt), params: { prompt: new_attributes }
        prompt.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the prompt" do
        prompt = Prompt.create! valid_attributes
        patch prompt_url(prompt), params: { prompt: new_attributes }
        prompt.reload
        expect(response).to redirect_to(prompt_url(prompt))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        prompt = Prompt.create! valid_attributes
        patch prompt_url(prompt), params: { prompt: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested prompt" do
      prompt = Prompt.create! valid_attributes
      expect {
        delete prompt_url(prompt)
      }.to change(Prompt, :count).by(-1)
    end

    it "redirects to the prompts list" do
      prompt = Prompt.create! valid_attributes
      delete prompt_url(prompt)
      expect(response).to redirect_to(prompts_url)
    end
  end
end
